CREATE DATABASE DB_NEPOTISMO
go
USE DB_NEPOTISMO
GO
CREATE TABLE TBL_PARENTESCO(
PAR_ID INT PRIMARY KEY IDENTITY,
PAR_DESCRIPCION VARCHAR(50) NOT NULL,
PAR_ESTADO CHAR (1) NOT NULL,
PAR_GRADO CHAR (1) NOT NULL
)
GO
CREATE TABLE TBL_EMPLEADOS(
EMP_ID INT PRIMARY KEY IDENTITY,
EMP_NOMBRE VARCHAR (50) NOT NULL,
EMP_APELLIDO VARCHAR (50) NOT NULL,
EMP_DNI VARCHAR(10) NOT NULL,
EMP_FECHA_NACIMIENTO DATE,
EMP_DIRECCION VARCHAR(500),
EMP_SEXO CHAR (1) NOT NULL,
EMP_ESTADO CHAR (1) NOT NULL
)
GO
CREATE TABLE TBL_PARENTESCO_EMPLEADO(
PXE_ID INT PRIMARY KEY IDENTITY,
PXE_DNI VARCHAR (10) NOT NULL,
PXE_NOMBRE VARCHAR(50) NOT NULL,
PXE_APELLIDO VARCHAR (50) NOT NULL,
PXE_DIRECCION VARCHAR (500) NOT NULL,
PXE_ESTADO CHAR(1) NOT NULL,
EMP_ID INT REFERENCES TBL_EMPLEADOS (EMP_ID) NOT NULL,
PAR_ID INT REFERENCES TBL_PARENTESCO (PAR_ID) NOT NULL
)
