CREATE DATABASE DB_PROCESAMIENTO_RPA
GO
USE DB_PROCESAMIENTO_RPA
GO
CREATE TABLE TBL_CURRICULUM(
CUR_DNI VARCHAR (10) PRIMARY KEY,
CUR_PATH VARCHAR (200) NOT NULL,
CUR_FECHA DATETIME
)
GO
CREATE TABLE TBL_EXTRACION_NLP(
EXT_ID INT PRIMARY KEY IDENTITY,
EXT_DESCRIPCION VARCHAR (500),
EXT_ENTIDAD VARCHAR (100),
EXT_FECHA_INGRESO DATE,
CUR_DNI VARCHAR (10) REFERENCES TBL_CURRICULUM (CUR_DNI)
)
GO
CREATE TABLE TBL_PROCESAMIENTO_NEPOTISMO(
NEP_ID INT PRIMARY KEY IDENTITY,
NEP_NOMBRE VARCHAR(50) NOT NULL,
NEP_APELLIDO VARCHAR (50) NOT NULL,
NEP_DIRECCION VARCHAR (500) NOT NULL,
NEP_PARENTESCO VARCHAR(50) NOT NULL,
NEP_GRADO CHAR (1) NOT NULL,
NEP_NOMBRE_EMPLEADO VARCHAR (50) NOT NULL,
NEP_APELLIDO_EMPLEADO VARCHAR (50) NOT NULL,
NEP_DNI_EMPLEADO VARCHAR(10) NOT NULL,
NEP_FECHA_NACIMIENTO_EMPLEADO DATE,
NEP_ESTADO_EMPLEADO CHAR (1) NOT NULL,
NEP_DNI VARCHAR (10) REFERENCES TBL_CURRICULUM (CUR_DNI),
NEP_FECHA_CONSULTA DATETIME
)
GO
CREATE TABLE TBL_PEP(
CUR_DNI VARCHAR(10) PRIMARY KEY REFERENCES TBL_CURRICULUM (CUR_DNI), 
PEP_FECHA_INICIO DATE NOT NULL, 
PEP_FECHA_FIN DATE,
PEP_DESCRIPCION_CARGO VARCHAR (100) NOT NULL,
PEP_MESES INT,
PEP_FECHA_CONSULTA DATETIME
)
GO
CREATE TABLE TBL_ANTECEDENTES_PENALES(
ANT_DNI VARCHAR(10) PRIMARY KEY REFERENCES TBL_CURRICULUM (CUR_DNI), 
ANT_NOMBRES VARCHAR (150) NOT NULL, 
ANT_ANTECEDENTE VARCHAR (2) NOT NULL,
ANT_SECLUSION VARCHAR (2) NOT NULL,
ANT_IDR INT NOT NULL,
ANT_TIPO_DOC VARCHAR (100) NOT NULL,
ANT_FECHA_CONSULTA DATETIME
)
GO
CREATE TABLE TBL_SENESCYT(
SEN_ID INT PRIMARY KEY IDENTITY,
SEN_DNI VARCHAR(10) REFERENCES TBL_CURRICULUM (CUR_DNI), 
SEN_FECHA DATE NOT NULL, 
SEN_INSTITUCION VARCHAR (200) NOT NULL,
SEN_NUMERO_REGISTRO VARCHAR (100) NOT NULL,
SEN_OBSERVACIONES VARCHAR (500),
SEN_RECONOCIDO VARCHAR (500) ,
SEN_TIPO VARCHAR (100) NOT NULL,
SEN_TITULO VARCHAR (200) NOT NULL, 
SEN_FECHA_CONSULTA DATETIME
)
GO


CREATE PROCEDURE PROC_EXTRACCION_NLP
@DNI VARCHAR (10),
@DESCRIPION VARCHAR (500),
@ENTIDAD VARCHAR (100)
AS
BEGIN
DECLARE @CANTIDAD INT
	SELECT @CANTIDAD=COUNT(*) FROM TBL_EXTRACION_NLP WHERE CUR_DNI=@DNI AND EXT_DESCRIPCION=@DESCRIPION AND EXT_ENTIDAD=@ENTIDAD
	IF @CANTIDAD=0
		BEGIN
			INSERT INTO TBL_EXTRACION_NLP VALUES (@DESCRIPION,@ENTIDAD,(SELECT GETDATE()),@DNI)
		END
END
GO
ALTER PROCEDURE PRO_RESULTADOS_RPA
@json NVARCHAR(MAX),
@fecha VARCHAR(50),
@bandera VARCHAR (50),
@dni VARCHAR (10)
AS
BEGIN

	IF @bandera='Pep001'
	BEGIN
	    --delete registro existente
		DELETE FROM TBL_PEP WHERE CUR_DNI=@dni
		--insert nuevo registros
		INSERT INTO TBL_PEP SELECT *,@fecha as PEP_FECHA_CONSULTA
		FROM OPENJSON(@json)
		  WITH (
			CUR_DNI VARCHAR(10) 'strict $.PEP_DNI',
			PEP_FECHA_INICIO DATE 'strict $.PEP_FECHA_INICIO', 
			PEP_FECHA_FIN DATE 'strict $.PEP_FECHA_FIN', 
			PEP_DESCRIPCION_CARGO VARCHAR (100) 'strict $.INST_DESCRIPCION', 
			PEP_MESES int 'strict $.MESES'
		  );
	END
	IF @bandera='Nepotismo001'
	BEGIN
		--delete registro existente
		DELETE FROM TBL_PROCESAMIENTO_NEPOTISMO 
		WHERE NEP_DNI=@dni
		AND NEP_DNI_EMPLEADO=(SELECT NEP_DNI_EMPLEADO FROM OPENJSON(@json) WITH (NEP_DNI_EMPLEADO VARCHAR(10) 'strict $.EMP_DNI'))
		 
		--insert nuevo registros
		INSERT INTO TBL_PROCESAMIENTO_NEPOTISMO SELECT *, @fecha as PEP_FECHA_CONSULTA
		FROM OPENJSON(@json)
		  WITH (
			NEP_NOMBRE VARCHAR(50) 'strict $.PXE_NOMBRE',
			NEP_APELLIDO VARCHAR (50) 'strict $.PXE_APELLIDO',
			NEP_DIRECCION VARCHAR (500) 'strict $.PXE_DIRECCION',
			NEP_PARENTESCO VARCHAR(50) 'strict $.PAR_DESCRIPCION',
			NEP_GRADO CHAR (1) 'strict $.PAR_GRADO',
			NEP_NOMBRE_EMPLEADO VARCHAR (50) 'strict $.EMP_NOMBRE',
			NEP_APELLIDO_EMPLEADO VARCHAR (50) 'strict $.EMP_APELLIDO',
			NEP_DNI_EMPLEADO VARCHAR(10) 'strict $.EMP_DNI',
			NEP_FECHA_NACIMIENTO_EMPLEADO DATE 'strict $.EMP_FECHA_NACIMIENTO',
			NEP_ESTADO_EMPLEADO CHAR (1) 'strict $.EMP_ESTADO',
			NEP_DNI VARCHAR (10) 'strict $.PXE_DNI'
			)
	END
	IF @bandera='AntecedentesPenales001'
	BEGIN
		--delete registro existente
		DELETE FROM TBL_ANTECEDENTES_PENALES WHERE ANT_DNI=@dni
		--insert nuevo registros
		INSERT INTO TBL_ANTECEDENTES_PENALES SELECT *, @fecha as PEP_FECHA_CONSULTA
		FROM OPENJSON(@json)
		  WITH (
			ANT_DNI VARCHAR(10)  'strict $.identity',
			ANT_NOMBRES VARCHAR (150) 'strict $.name',
			ANT_ANTECEDENTE VARCHAR (2) 'strict $.antecedent',
			ANT_SECLUSION VARCHAR (2) 'strict $.seclusion',
			ANT_IDR INT  'strict $.idr',
			ANT_TIPO_DOC VARCHAR (100)  'strict $.type'
			)
	END
	IF @bandera='Senescyt001'
	BEGIN
		--delete registro existente
		DELETE FROM TBL_SENESCYT WHERE SEN_DNI=@dni
		AND SEN_NUMERO_REGISTRO=(SELECT SEN_NUMERO_REGISTRO FROM OPENJSON(@json) WITH (SEN_NUMERO_REGISTRO VARCHAR(100) 'strict $.NumeroRegistro'))
		--insert nuevo registros
		INSERT INTO TBL_SENESCYT SELECT @dni,*,@fecha as PEP_FECHA_CONSULTA
		FROM OPENJSON(@json)
		  WITH (
			SEN_FECHA DATE 'strict $.FechaRegistro',
			SEN_INSTITUCION VARCHAR (200) 'strict $.Institucion',
			SEN_NUMERO_REGISTRO VARCHAR (100) 'strict $.NumeroRegistro',
			SEN_OBSERVACIONES VARCHAR (500) 'strict $.Observacion',
			SEN_RECONOCIDO VARCHAR (500) 'strict $.Reconocido',
			SEN_TIPO VARCHAR (100) 'strict $.Tipo',
			SEN_TITULO VARCHAR (200) 'strict $.Titulo'
			)
	END 

END