CREATE DATABASE DB_PEPS
GO
USE DB_PEPS
GO
CREATE TABLE TBL_INSTITUCION(
INST_ID INT PRIMARY KEY IDENTITY,
INST_DESCRIPCION VARCHAR (100) NOT NULL,
INST_TELEFONO VARCHAR(100),
INST_DIRECCION VARCHAR(100)
)
GO
CREATE TABLE TBL_PERSONAS_PEP(
PEP_ID INT PRIMARY KEY IDENTITY,
PEP_NOMBRE VARCHAR (50) NOT NULL,
PEP_APELLIDO VARCHAR (50) NOT NULL,
PEP_DNI VARCHAR(10) NOT NULL, 
PEP_FECHA_INICIO DATE NOT NULL, 
PEP_FECHA_FIN DATE,
PEP_TRABAJO_ACTUAL CHAR (1) NOT NULL, 
INST_ID INT REFERENCES TBL_INSTITUCION (INST_ID)
)
